# Generated by Django 4.1.1 on 2022-10-05 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instapost', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instapost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instaposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instacomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instacomment',
            name='instapost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instapost.instapost'),
        ),
        migrations.AddField(
            model_name='image',
            name='instapost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='instapost.instapost'),
        ),
    ]
