# Generated by Django 4.1.1 on 2022-10-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instapost',
            old_name='nickname',
            new_name='author',
        ),
    ]
