# Generated by Django 4.1.1 on 2022-10-04 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instapost', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instapost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instaposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
