# Generated by Django 4.1.1 on 2022-10-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0008_image_remove_instapost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
