# Generated by Django 4.1.1 on 2022-10-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0004_rename_comment_author_instacomment_author'),
        ('instapost', '0009_edit_time'),
    ]

    operations = [
    ]
