# Generated by Django 4.1.1 on 2022-10-04 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0010_merge_20221004_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='instapost',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='instapost.instapost'),
        ),
    ]
