# Generated by Django 4.1.1 on 2022-10-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0012_alter_image_instapost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='instapost',
        ),
    ]
