# Generated by Django 4.1.1 on 2022-10-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0010_merge_20221004_1734'),
        ('instapost', '0011_alter_instacomment_instapost'),
        ('instapost', '0013_remove_image_instapost'),
    ]

    operations = [
    ]
