# Generated by Django 4.1.1 on 2022-09-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instauser', '0002_alter_instauser_is_dating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instauser',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
