# Generated by Django 4.1.1 on 2022-09-30 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instauser', '0003_alter_instauser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instauser',
            name='username',
        ),
    ]
